services:
  - type: web
    name: powerpoint-presentation-generator
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
